[game]
hostname = "[EN][MRP] Final Frontier | Meridian"
desc = "A ship-based fork with emphasis on actual player interaction. Engage in ship or ground combat as one of three factions, or simply live out your life as a salvager or mercenary."
